version: "3.8"
services:
  app:
    build: .
    volumes:
      - huggingface_cache:/root/.cache/huggingface
      - ollama_cache:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  huggingface_cache:
  ollama_cache:
