# === Database ===
CONTENTFUL_MANAGEMENT_API_TOKEN = ""
CONTENTFUL_SPACE_ID = ""
CONTENTFUL_ENVIRONMENT_ID = ""

# === Image Diffusion ===
HUGGINGFACE_DIFFUSERS_PRETRAINED_MODEL_NAME_OR_PATH = ""

# === LLM Text Generation ===
OLLAMA_MODEL = ""
OLLAMA_TEMPERATURE = 1
