# === Database ===
CONTENTFUL_MANAGEMENT_API_TOKEN = ""
CONTENTFUL_SPACE_ID = ""
CONTENTFUL_ENVIRONMENT_ID = ""

# === Image Diffusion ===
HUGGINGFACE_DIFFUSERS_PRETRAINED_MODEL_NAME_OR_PATH = (
    "stablediffusionapi/juggernaut-xl-v7"
)

# === LLM Text Generation ===
OLLAMA_MODEL = "mistral-openorca"
OLLAMA_TEMPERATURE_IDEA_GENERATOR = 10
OLLAMA_TEMPERATURE_WRITER = 0.8
